pipeline {

    agent any

    tools {
        jdk 'JDK21'
        maven 'Maven3'
    }

    parameters {

        string(
            name: 'PROJECT_PATH',
            defaultValue: 'C:/Users/tenzin.tamang/Downloads/EmployeeManagementSystem/EmployeeManagementSystem',
            description: 'Project Location'
        )

        choice(
            name: 'BUILD_MODE',
            choices: ['BUILD_AND_RUN', 'RUN_ONLY'],
            description: 'Build and run or only run'
        )

        string(
            name: 'APP_PORT',
            defaultValue: '8085',
            description: 'Application Port'
        )

        choice(
            name: 'DEBUG_MODE',
            choices: ['ENABLE', 'DISABLE'],
            description: 'Enable or Disable Debug'
        )

        string(
            name: 'MIN_COVERAGE',
            defaultValue: '80',
            description: 'Minimum Coverage Required'
        )
    }

    stages {

        stage('Input Validation') {

            steps {

                script {

                    echo "Checking Project Path..."

                    if (!fileExists("${params.PROJECT_PATH}/pom.xml")) {
                        error "pom.xml not found"
                    }

                    echo "Project validation successful"
                }
            }
        }

        stage('Workspace Preparation') {

            steps {

                dir("${params.PROJECT_PATH}") {

                    bat 'mvn clean'

                }
            }
        }

        stage('Build') {

            when {
                expression {
                    params.BUILD_MODE == 'BUILD_AND_RUN'
                }
            }

            steps {

                dir("${params.PROJECT_PATH}") {

                    bat 'mvn compile'

                }
            }
        }

        stage('Run Unit Tests & Coverage') {

            steps {

                dir("${params.PROJECT_PATH}") {

                    bat 'mvn test jacoco:report'

                    junit 'target/surefire-reports/*.xml'

                    script {

                        def report =
                        readFile('target/site/jacoco/jacoco.csv')

                        def lines = report.split('\n')

                        def lastLine = lines[-1].split(',')

                        def instructionMissed =
                        lastLine[3].toInteger()

                        def instructionCovered =
                        lastLine[4].toInteger()

                        def coverage =
                        (instructionCovered * 100) /
                        (instructionCovered + instructionMissed)

                        echo "Coverage: ${coverage}%"

                        if (coverage < params.MIN_COVERAGE.toInteger()) {

                            error "Coverage below threshold"

                        } else {

                            echo "Coverage requirement satisfied"

                        }
                    }
                }
            }
        }

        stage('Secure Configuration') {

            steps {

                withCredentials([

                    string(
                        credentialsId: 'DB_USERNAME',
                        variable: 'SECURE_DB_USER'
                    ),

                    string(
                        credentialsId: 'DB_PASSWORD',
                        variable: 'SECURE_DB_PASS'
                    )

                ]) {

                    echo "Database credentials loaded securely"

                }
            }
        }

        stage('Application Execution') {

            when {
                expression {
                    params.BUILD_MODE == 'BUILD_AND_RUN'
                }
            }

            steps {

                withCredentials([

                    string(
                        credentialsId: 'DB_USERNAME',
                        variable: 'SECURE_DB_USER'
                    ),

                    string(
                        credentialsId: 'DB_PASSWORD',
                        variable: 'SECURE_DB_PASS'
                    )

                ]) {

                    dir("${params.PROJECT_PATH}") {

                        bat """
                        start java -jar target\\demo-0.0.1-SNAPSHOT.jar ^
                        --server.port=${params.APP_PORT} ^
                        --spring.datasource.username=%SECURE_DB_USER% ^
                        --spring.datasource.password=%SECURE_DB_PASS%
                        """

                    }
                }
            }
        }

        stage('Health Check') {

            steps {

                bat """
                curl http://localhost:${params.APP_PORT}/actuator/health
                """
            }
        }

        stage('Summary') {

            steps {

                echo "Build Success"

                echo "Tests Passed"

                echo "Coverage Verified"

                echo "Application Running On Port ${params.APP_PORT}"
            }
        }
    }

    post {

        always {

            cleanWs()

            echo "Pipeline Finished"

        }

        success {

            echo "Pipeline Executed Successfully"

        }

        failure {

            echo "Pipeline Failed"

        }
    }
}